// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OverwatchCore.Data;
//
//    var rawPlayerStats = RawPlayerStats.FromJson(jsonString);

namespace OverwatchCore.Data
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using OverwatchCore.Enums;

    internal partial class RawPlayerStats
    {
        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        internal Uri Icon { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        internal string Name { get; set; }

        [JsonProperty("level", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Level { get; set; }

        [JsonProperty("levelIcon", NullValueHandling = NullValueHandling.Ignore)]
        internal Uri LevelIcon { get; set; }

        [JsonProperty("endorsement", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Endorsement { get; set; }

        [JsonProperty("endorsementIcon", NullValueHandling = NullValueHandling.Ignore)]
        internal Uri EndorsementIcon { get; set; }

        [JsonProperty("prestige", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Prestige { get; set; }

        [JsonProperty("prestigeIcon", NullValueHandling = NullValueHandling.Ignore)]
        internal Uri PrestigeIcon { get; set; }

        [JsonProperty("rating", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Rating { get; set; }

        [JsonProperty("ratingIcon", NullValueHandling = NullValueHandling.Ignore)]
        internal Uri RatingIcon { get; set; }

        [JsonProperty("gamesWon", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GamesWon { get; set; }

        [JsonProperty("quickPlayStats", NullValueHandling = NullValueHandling.Ignore)]
        internal RawStats QuickPlayStats { get; set; }

        [JsonProperty("competitiveStats", NullValueHandling = NullValueHandling.Ignore)]
        internal RawStats CompetitiveStats { get; set; }

        [JsonProperty("private", NullValueHandling = NullValueHandling.Ignore)]
        internal bool? Private { get; set; }
    }

    internal partial class RawStats
    {
        [JsonProperty("topHeroes", NullValueHandling = NullValueHandling.Ignore)]
        internal Dictionary<string, TopHero> TopHeroes { get; set; }

        [JsonProperty("careerStats", NullValueHandling = NullValueHandling.Ignore)]
        internal RawCareerStats CareerStats { get; set; }
    }

    internal partial class RawCareerStats
    {
        [JsonProperty("allHeroes", NullValueHandling = NullValueHandling.Ignore)]
        internal Hero AllHeroes { get; set; }

        [JsonProperty("ana", NullValueHandling = NullValueHandling.Ignore)]
        internal Ana Ana { get; set; }

        [JsonProperty("ashe", NullValueHandling = NullValueHandling.Ignore)]
        internal Ashe Ashe { get; set; }

        [JsonProperty("bastion", NullValueHandling = NullValueHandling.Ignore)]
        internal Bastion Bastion { get; set; }

        [JsonProperty("brigitte", NullValueHandling = NullValueHandling.Ignore)]
        internal Brigitte Brigitte { get; set; }

        [JsonProperty("dVa", NullValueHandling = NullValueHandling.Ignore)]
        internal DVa DVa { get; set; }

        [JsonProperty("doomfist", NullValueHandling = NullValueHandling.Ignore)]
        internal Doomfist Doomfist { get; set; }

        [JsonProperty("hanzo", NullValueHandling = NullValueHandling.Ignore)]
        internal Hanzo Hanzo { get; set; }

        [JsonProperty("junkrat", NullValueHandling = NullValueHandling.Ignore)]
        internal Junkrat Junkrat { get; set; }

        [JsonProperty("lucio", NullValueHandling = NullValueHandling.Ignore)]
        internal Lucio Lucio { get; set; }

        [JsonProperty("mccree", NullValueHandling = NullValueHandling.Ignore)]
        internal Mccree Mccree { get; set; }

        [JsonProperty("mei", NullValueHandling = NullValueHandling.Ignore)]
        internal Mei Mei { get; set; }

        [JsonProperty("mercy", NullValueHandling = NullValueHandling.Ignore)]
        internal Mercy Mercy { get; set; }

        [JsonProperty("moira", NullValueHandling = NullValueHandling.Ignore)]
        internal Moira Moira { get; set; }

        [JsonProperty("orisa", NullValueHandling = NullValueHandling.Ignore)]
        internal Orisa Orisa { get; set; }

        [JsonProperty("pharah", NullValueHandling = NullValueHandling.Ignore)]
        internal Pharah Pharah { get; set; }

        [JsonProperty("reaper", NullValueHandling = NullValueHandling.Ignore)]
        internal Reaper Reaper { get; set; }

        [JsonProperty("reinhardt", NullValueHandling = NullValueHandling.Ignore)]
        internal Reinhardt Reinhardt { get; set; }

        [JsonProperty("roadhog", NullValueHandling = NullValueHandling.Ignore)]
        internal Roadhog Roadhog { get; set; }

        [JsonProperty("soldier76", NullValueHandling = NullValueHandling.Ignore)]
        internal Soldier76 Soldier76 { get; set; }

        [JsonProperty("sombra", NullValueHandling = NullValueHandling.Ignore)]
        internal Sombra Sombra { get; set; }

        [JsonProperty("symmetra", NullValueHandling = NullValueHandling.Ignore)]
        internal Symmetra Symmetra { get; set; }

        [JsonProperty("torbjorn", NullValueHandling = NullValueHandling.Ignore)]
        internal Torbjorn Torbjorn { get; set; }

        [JsonProperty("tracer", NullValueHandling = NullValueHandling.Ignore)]
        internal Tracer Tracer { get; set; }

        [JsonProperty("widowmaker", NullValueHandling = NullValueHandling.Ignore)]
        internal Widowmaker Widowmaker { get; set; }

        [JsonProperty("winston", NullValueHandling = NullValueHandling.Ignore)]
        internal Winston Winston { get; set; }

        [JsonProperty("wreckingBall", NullValueHandling = NullValueHandling.Ignore)]
        internal WreckingBall WreckingBall { get; set; }

        [JsonProperty("zarya", NullValueHandling = NullValueHandling.Ignore)]
        internal Zarya Zarya { get; set; }

        [JsonProperty("zenyatta", NullValueHandling = NullValueHandling.Ignore)]
        internal Zenyatta Zenyatta { get; set; }
    }

    internal partial class Hero
    {
        [JsonProperty("assists", NullValueHandling = NullValueHandling.Ignore)]
        internal Assists Assists { get; set; }

        [JsonProperty("average", NullValueHandling = NullValueHandling.Ignore)]
        internal Average Average { get; set; }

        [JsonProperty("best", NullValueHandling = NullValueHandling.Ignore)]
        internal Best Best { get; set; }

        [JsonProperty("combat", NullValueHandling = NullValueHandling.Ignore)]
        internal Combat Combat { get; set; }

        [JsonProperty("deaths", NullValueHandling = NullValueHandling.Ignore)]
        internal string Deaths { get; set; }

        [JsonProperty("game", NullValueHandling = NullValueHandling.Ignore)]
        internal Game Game { get; set; }

        [JsonProperty("matchAwards", NullValueHandling = NullValueHandling.Ignore)]
        internal MatchAwards MatchAwards { get; set; }

        [JsonProperty("miscellaneous", NullValueHandling = NullValueHandling.Ignore)]
        internal Miscellaneous Miscellaneous { get; set; }
    }

    internal partial class Assists
    {
        [JsonProperty("defensiveAssists", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DefensiveAssists { get; set; }

        [JsonProperty("defensiveAssistsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DefensiveAssistsAvgPer10Min { get; set; }

        [JsonProperty("defensiveAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DefensiveAssistsMostInGame { get; set; }

        [JsonProperty("healingDone", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HealingDone { get; set; }

        [JsonProperty("healingDoneAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? HealingDoneAvgPer10Min { get; set; }

        [JsonProperty("healingDoneMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HealingDoneMostInGame { get; set; }

        [JsonProperty("offensiveAssists", NullValueHandling = NullValueHandling.Ignore)]
        internal long? OffensiveAssists { get; set; }

        [JsonProperty("offensiveAssistsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? OffensiveAssistsAvgPer10Min { get; set; }

        [JsonProperty("offensiveAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? OffensiveAssistsMostInGame { get; set; }

        [JsonProperty("reconAssists", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ReconAssists { get; set; }

        [JsonProperty("reconAssistsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ReconAssistsAvgPer10Min { get; set; }

        [JsonProperty("reconAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ReconAssistsMostInGame { get; set; }
    }

    internal partial class Average
    {
        [JsonProperty("allDamageDoneAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? AllDamageDoneAvgPer10Min { get; set; }

        [JsonProperty("barrierDamageDoneAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? BarrierDamageDoneAvgPer10Min { get; set; }

        [JsonProperty("deathsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DeathsAvgPer10Min { get; set; }

        [JsonProperty("eliminationsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EliminationsAvgPer10Min { get; set; }

        [JsonProperty("finalBlowsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? FinalBlowsAvgPer10Min { get; set; }

        [JsonProperty("healingDoneAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? HealingDoneAvgPer10Min { get; set; }

        [JsonProperty("heroDamageDoneAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? HeroDamageDoneAvgPer10Min { get; set; }

        [JsonProperty("objectiveKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ObjectiveKillsAvgPer10Min { get; set; }

        [JsonProperty("objectiveTimeAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal EAvgPer10Min? ObjectiveTimeAvgPer10Min { get; set; }

        [JsonProperty("soloKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SoloKillsAvgPer10Min { get; set; }

        [JsonProperty("timeSpentOnFireAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal EAvgPer10Min? TimeSpentOnFireAvgPer10Min { get; set; }

        [JsonProperty("eliminationsPerLife", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EliminationsPerLife { get; set; }

        [JsonProperty("meleeFinalBlowsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeleeFinalBlowsAvgPer10Min { get; set; }

        [JsonProperty("criticalHitsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? CriticalHitsAvgPer10Min { get; set; }
    }

    internal partial class Best
    {
        [JsonProperty("allDamageDoneMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? AllDamageDoneMostInGame { get; set; }

        [JsonProperty("allDamageDoneMostInLife", NullValueHandling = NullValueHandling.Ignore)]
        internal long? AllDamageDoneMostInLife { get; set; }

        [JsonProperty("barrierDamageDoneMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BarrierDamageDoneMostInGame { get; set; }

        [JsonProperty("criticalHitsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CriticalHitsMostInGame { get; set; }

        [JsonProperty("criticalHitsMostInLife", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CriticalHitsMostInLife { get; set; }

        [JsonProperty("defensiveAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DefensiveAssistsMostInGame { get; set; }

        [JsonProperty("eliminationsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EliminationsMostInGame { get; set; }

        [JsonProperty("eliminationsMostInLife", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EliminationsMostInLife { get; set; }

        [JsonProperty("environmentalKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnvironmentalKillsMostInGame { get; set; }

        [JsonProperty("finalBlowsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? FinalBlowsMostInGame { get; set; }

        [JsonProperty("healingDoneMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HealingDoneMostInGame { get; set; }

        [JsonProperty("heroDamageDoneMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HeroDamageDoneMostInGame { get; set; }

        [JsonProperty("heroDamageDoneMostInLife", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HeroDamageDoneMostInLife { get; set; }

        [JsonProperty("killsStreakBest", NullValueHandling = NullValueHandling.Ignore)]
        internal long? KillsStreakBest { get; set; }

        [JsonProperty("meleeFinalBlowsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeleeFinalBlowsMostInGame { get; set; }

        [JsonProperty("multikillsBest", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MultikillsBest { get; set; }

        [JsonProperty("objectiveKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ObjectiveKillsMostInGame { get; set; }

        [JsonProperty("objectiveTimeMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string ObjectiveTimeMostInGame { get; set; }

        [JsonProperty("offensiveAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? OffensiveAssistsMostInGame { get; set; }

        [JsonProperty("reconAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ReconAssistsMostInGame { get; set; }

        [JsonProperty("soloKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SoloKillsMostInGame { get; set; }

        [JsonProperty("teleporterPadsDestroyedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TeleporterPadsDestroyedMostInGame { get; set; }

        [JsonProperty("timeSpentOnFireMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string TimeSpentOnFireMostInGame { get; set; }

        [JsonProperty("turretsDestroyedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TurretsDestroyedMostInGame { get; set; }
    }

    internal partial class Combat
    {
        [JsonProperty("barrierDamageDone", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BarrierDamageDone { get; set; }

        [JsonProperty("damageDone", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageDone { get; set; }

        [JsonProperty("deaths", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Deaths { get; set; }

        [JsonProperty("eliminations", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Eliminations { get; set; }

        [JsonProperty("environmentalKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnvironmentalKills { get; set; }

        [JsonProperty("finalBlows", NullValueHandling = NullValueHandling.Ignore)]
        internal long? FinalBlows { get; set; }

        [JsonProperty("heroDamageDone", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HeroDamageDone { get; set; }

        [JsonProperty("meleeFinalBlows", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeleeFinalBlows { get; set; }

        [JsonProperty("multikills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Multikills { get; set; }

        [JsonProperty("objectiveKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ObjectiveKills { get; set; }

        [JsonProperty("objectiveTime", NullValueHandling = NullValueHandling.Ignore)]
        internal string ObjectiveTime { get; set; }

        [JsonProperty("soloKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SoloKills { get; set; }

        [JsonProperty("timeSpentOnFire", NullValueHandling = NullValueHandling.Ignore)]
        internal string TimeSpentOnFire { get; set; }

        [JsonProperty("quickMeleeAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string QuickMeleeAccuracy { get; set; }

        [JsonProperty("weaponAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string WeaponAccuracy { get; set; }

        [JsonProperty("criticalHits", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CriticalHits { get; set; }

        [JsonProperty("criticalHitsAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string CriticalHitsAccuracy { get; set; }
    }

    internal partial class Game
    {
        [JsonProperty("gamesLost", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GamesLost { get; set; }

        [JsonProperty("gamesPlayed", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GamesPlayed { get; set; }

        [JsonProperty("gamesTied", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GamesTied { get; set; }

        [JsonProperty("gamesWon", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GamesWon { get; set; }

        [JsonProperty("timePlayed", NullValueHandling = NullValueHandling.Ignore)]
        internal string TimePlayed { get; set; }

        [JsonProperty("winPercentage", NullValueHandling = NullValueHandling.Ignore)]
        internal string WinPercentage { get; set; }
    }

    internal partial class MatchAwards
    {
        [JsonProperty("cards", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Cards { get; set; }

        [JsonProperty("medals", NullValueHandling = NullValueHandling.Ignore)]
        internal long? Medals { get; set; }

        [JsonProperty("medalsBronze", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MedalsBronze { get; set; }

        [JsonProperty("medalsGold", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MedalsGold { get; set; }

        [JsonProperty("medalsSilver", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MedalsSilver { get; set; }
    }

    internal partial class Miscellaneous
    {
        [JsonProperty("teleporterPadsDestroyed", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TeleporterPadsDestroyed { get; set; }

        [JsonProperty("turretsDestroyed", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TurretsDestroyed { get; set; }
    }

    internal partial class Ana : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal AnaHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class AnaHeroSpecific
    {
        [JsonProperty("bioticGrenadeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BioticGrenadeKills { get; set; }

        [JsonProperty("enemiesSlept", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesSlept { get; set; }

        [JsonProperty("enemiesSleptAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EnemiesSleptAvgPer10Min { get; set; }

        [JsonProperty("enemiesSleptMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesSleptMostInGame { get; set; }

        [JsonProperty("nanoBoostAssists", NullValueHandling = NullValueHandling.Ignore)]
        internal long? NanoBoostAssists { get; set; }

        [JsonProperty("nanoBoostAssistsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? NanoBoostAssistsAvgPer10Min { get; set; }

        [JsonProperty("nanoBoostAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? NanoBoostAssistsMostInGame { get; set; }

        [JsonProperty("nanoBoostsApplied", NullValueHandling = NullValueHandling.Ignore)]
        internal long? NanoBoostsApplied { get; set; }

        [JsonProperty("nanoBoostsAppliedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? NanoBoostsAppliedAvgPer10Min { get; set; }

        [JsonProperty("nanoBoostsAppliedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? NanoBoostsAppliedMostInGame { get; set; }

        [JsonProperty("scopedAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedAccuracy { get; set; }

        [JsonProperty("scopedAccuracyBestInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedAccuracyBestInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("unscopedAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string UnscopedAccuracy { get; set; }

        [JsonProperty("unscopedAccuracyBestInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string UnscopedAccuracyBestInGame { get; set; }
    }

    internal partial class Ashe : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal AsheHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class AsheHeroSpecific
    {
        [JsonProperty("bobKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BobKills { get; set; }

        [JsonProperty("bobKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BobKillsAvgPer10Min { get; set; }

        [JsonProperty("bobKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BobKillsMostInGame { get; set; }

        [JsonProperty("coachGunKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CoachGunKills { get; set; }

        [JsonProperty("coachGunKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CoachGunKillsAvgPer10Min { get; set; }

        [JsonProperty("coachGunKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CoachGunKillsMostInGame { get; set; }

        [JsonProperty("scopedAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedAccuracy { get; set; }

        [JsonProperty("scopedAccuracyBestInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedAccuracyBestInGame { get; set; }

        [JsonProperty("scopedCriticalHitKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScopedCriticalHitKills { get; set; }

        [JsonProperty("scopedCriticalHits", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScopedCriticalHits { get; set; }

        [JsonProperty("scopedCriticalHitsAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedCriticalHitsAccuracy { get; set; }

        [JsonProperty("scopedCriticalHitsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ScopedCriticalHitsAvgPer10Min { get; set; }

        [JsonProperty("scopedCriticalHitsKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScopedCriticalHitsKillsAvgPer10Min { get; set; }

        [JsonProperty("scopedCriticalHitsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScopedCriticalHitsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("dynamiteKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DynamiteKills { get; set; }

        [JsonProperty("dynamiteKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DynamiteKillsAvgPer10Min { get; set; }

        [JsonProperty("dynamiteKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DynamiteKillsMostInGame { get; set; }
    }

    internal partial class Bastion : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal BastionHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class BastionHeroSpecific
    {
        [JsonProperty("reconKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ReconKills { get; set; }

        [JsonProperty("reconKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ReconKillsAvgPer10Min { get; set; }

        [JsonProperty("reconKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ReconKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("sentryKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SentryKills { get; set; }

        [JsonProperty("sentryKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SentryKillsAvgPer10Min { get; set; }

        [JsonProperty("sentryKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SentryKillsMostInGame { get; set; }

        [JsonProperty("tankKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TankKills { get; set; }

        [JsonProperty("tankKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TankKillsAvgPer10Min { get; set; }

        [JsonProperty("tankKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TankKillsMostInGame { get; set; }
    }

    internal partial class Brigitte : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal BrigitteHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class BrigitteHeroSpecific
    {
        [JsonProperty("armorProvided", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ArmorProvided { get; set; }

        [JsonProperty("armorProvidedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ArmorProvidedAvgPer10Min { get; set; }

        [JsonProperty("armorProvidedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ArmorProvidedMostInGame { get; set; }

        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("inspireUptimePercentage", NullValueHandling = NullValueHandling.Ignore)]
        internal string InspireUptimePercentage { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }
    }

    internal partial class DVa : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal DVaHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class DVaHeroSpecific
    {
        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("mechDeaths", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MechDeaths { get; set; }

        [JsonProperty("mechsCalled", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MechsCalled { get; set; }

        [JsonProperty("mechsCalledAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? MechsCalledAvgPer10Min { get; set; }

        [JsonProperty("mechsCalledMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MechsCalledMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfDestructKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfDestructKills { get; set; }

        [JsonProperty("selfDestructKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfDestructKillsAvgPer10Min { get; set; }

        [JsonProperty("selfDestructKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfDestructKillsMostInGame { get; set; }
    }

    internal partial class Doomfist : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal DoomfistHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class DoomfistHeroSpecific
    {
        [JsonProperty("abilityDamageDone", NullValueHandling = NullValueHandling.Ignore)]
        internal long? AbilityDamageDone { get; set; }

        [JsonProperty("abilityDamageDoneAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? AbilityDamageDoneAvgPer10Min { get; set; }

        [JsonProperty("abilityDamageDoneMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? AbilityDamageDoneMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("shieldsCreated", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ShieldsCreated { get; set; }

        [JsonProperty("shieldsCreatedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ShieldsCreatedAvgPer10Min { get; set; }

        [JsonProperty("shieldsCreatedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ShieldsCreatedMostInGame { get; set; }

        [JsonProperty("meteorStrikeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeteorStrikeKills { get; set; }

        [JsonProperty("meteorStrikeKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeteorStrikeKillsAvgPer10Min { get; set; }

        [JsonProperty("meteorStrikeKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeteorStrikeKillsMostInGame { get; set; }
    }

    internal partial class Genji : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal GenjiHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class GenjiHeroSpecific
    {
        [JsonProperty("damageReflected", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageReflected { get; set; }

        [JsonProperty("damageReflectedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageReflectedAvgPer10Min { get; set; }

        [JsonProperty("damageReflectedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageReflectedMostInGame { get; set; }

        [JsonProperty("deflectionKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DeflectionKills { get; set; }

        [JsonProperty("dragonbladesKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DragonbladesKills { get; set; }

        [JsonProperty("dragonbladesKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DragonbladesKillsAvgPer10Min { get; set; }

        [JsonProperty("dragonbladesKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DragonbladesKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }
    }

    internal partial class Hanzo : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal HanzoHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class HanzoHeroSpecific
    {
        [JsonProperty("dragonstrikeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DragonstrikeKills { get; set; }

        [JsonProperty("dragonstrikeKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DragonstrikeKillsAvgPer10Min { get; set; }

        [JsonProperty("dragonstrikeKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DragonstrikeKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("stormArrowKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? StormArrowKills { get; set; }

        [JsonProperty("stormArrowKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? StormArrowKillsAvgPer10Min { get; set; }

        [JsonProperty("stormArrowKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? StormArrowKillsMostInGame { get; set; }

        [JsonProperty("scatterArrowKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScatterArrowKills { get; set; }

        [JsonProperty("scatterArrowKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ScatterArrowKillsAvgPer10Min { get; set; }

        [JsonProperty("scatterArrowKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScatterArrowKillsMostInGame { get; set; }
    }

    internal partial class Junkrat : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal JunkratHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class JunkratHeroSpecific
    {
        [JsonProperty("concussionMineKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ConcussionMineKills { get; set; }

        [JsonProperty("concussionMineKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ConcussionMineKillsAvgPer10Min { get; set; }

        [JsonProperty("concussionMineKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ConcussionMineKillsMostInGame { get; set; }

        [JsonProperty("enemiesTrapped", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesTrapped { get; set; }

        [JsonProperty("enemiesTrappedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EnemiesTrappedAvgPer10Min { get; set; }

        [JsonProperty("enemiesTrappedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesTrappedMostInGame { get; set; }

        [JsonProperty("ripTireKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? RipTireKills { get; set; }

        [JsonProperty("ripTireKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? RipTireKillsAvgPer10Min { get; set; }

        [JsonProperty("ripTireKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? RipTireKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }
    }

    internal partial class Lucio : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal LucioHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class LucioHeroSpecific
    {
        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("soundBarriersProvided", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SoundBarriersProvided { get; set; }

        [JsonProperty("soundBarriersProvidedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SoundBarriersProvidedAvgPer10Min { get; set; }

        [JsonProperty("soundBarriersProvidedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SoundBarriersProvidedMostInGame { get; set; }
    }

    internal partial class Mccree : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal MccreeHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class MccreeHeroSpecific
    {
        [JsonProperty("deadeyeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DeadeyeKills { get; set; }

        [JsonProperty("deadeyeKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DeadeyeKillsAvgPer10Min { get; set; }

        [JsonProperty("deadeyeKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DeadeyeKillsMostInGame { get; set; }

        [JsonProperty("fanTheHammerKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? FanTheHammerKills { get; set; }

        [JsonProperty("fanTheHammerKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? FanTheHammerKillsAvgPer10Min { get; set; }

        [JsonProperty("fanTheHammerKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? FanTheHammerKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }
    }

    internal partial class Mei : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal MeiHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class MeiHeroSpecific
    {
        [JsonProperty("blizzardKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BlizzardKills { get; set; }

        [JsonProperty("blizzardKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BlizzardKillsAvgPer10Min { get; set; }

        [JsonProperty("blizzardKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BlizzardKillsMostInGame { get; set; }

        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("enemiesFrozen", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesFrozen { get; set; }

        [JsonProperty("enemiesFrozenAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EnemiesFrozenAvgPer10Min { get; set; }

        [JsonProperty("enemiesFrozenMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesFrozenMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }
    }

    internal partial class Mercy : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal MercyHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class MercyHeroSpecific
    {
        [JsonProperty("damageAmplified", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageAmplified { get; set; }

        [JsonProperty("damageAmplifiedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageAmplifiedAvgPer10Min { get; set; }

        [JsonProperty("damageAmplifiedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageAmplifiedMostInGame { get; set; }

        [JsonProperty("playersResurrected", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersResurrected { get; set; }

        [JsonProperty("playersResurrectedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? PlayersResurrectedAvgPer10Min { get; set; }

        [JsonProperty("playersResurrectedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersResurrectedMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("blasterKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BlasterKills { get; set; }

        [JsonProperty("blasterKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BlasterKillsAvgPer10Min { get; set; }

        [JsonProperty("blasterKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BlasterKillsMostInGame { get; set; }
    }

    internal partial class Moira : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal MoiraHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class MoiraHeroSpecific
    {
        [JsonProperty("coalescenceHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CoalescenceHealing { get; set; }

        [JsonProperty("coalescenceHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? CoalescenceHealingAvgPer10Min { get; set; }

        [JsonProperty("coalescenceHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CoalescenceHealingMostInGame { get; set; }

        [JsonProperty("coalescenceKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CoalescenceKills { get; set; }

        [JsonProperty("coalescenceKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? CoalescenceKillsAvgPer10Min { get; set; }

        [JsonProperty("coalescenceKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? CoalescenceKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }
    }

    internal partial class Orisa : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal OrisaHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class OrisaHeroSpecific
    {
        [JsonProperty("damageAmplified", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageAmplified { get; set; }

        [JsonProperty("damageAmplifiedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageAmplifiedAvgPer10Min { get; set; }

        [JsonProperty("damageAmplifiedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageAmplifiedMostInGame { get; set; }

        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("superchargerAssists", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SuperchargerAssists { get; set; }

        [JsonProperty("superchargerAssistsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SuperchargerAssistsAvgPer10Min { get; set; }

        [JsonProperty("superchargerAssistsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SuperchargerAssistsMostInGame { get; set; }
    }

    internal partial class Pharah : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal PharahHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class PharahHeroSpecific
    {
        [JsonProperty("barrageKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BarrageKills { get; set; }

        [JsonProperty("barrageKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? BarrageKillsAvgPer10Min { get; set; }

        [JsonProperty("barrageKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BarrageKillsMostInGame { get; set; }

        [JsonProperty("directHitsAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string DirectHitsAccuracy { get; set; }

        [JsonProperty("rocketDirectHits", NullValueHandling = NullValueHandling.Ignore)]
        internal long? RocketDirectHits { get; set; }

        [JsonProperty("rocketDirectHitsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? RocketDirectHitsAvgPer10Min { get; set; }

        [JsonProperty("rocketDirectHitsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? RocketDirectHitsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }
    }

    internal partial class Reaper : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal ReaperHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class ReaperHeroSpecific
    {
        [JsonProperty("deathsBlossomKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DeathsBlossomKills { get; set; }

        [JsonProperty("deathsBlossomKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DeathsBlossomKillsAvgPer10Min { get; set; }

        [JsonProperty("deathsBlossomKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DeathsBlossomKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }
    }

    internal partial class Reinhardt : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal ReinhardtHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class ReinhardtHeroSpecific
    {
        [JsonProperty("chargeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ChargeKills { get; set; }

        [JsonProperty("chargeKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ChargeKillsAvgPer10Min { get; set; }

        [JsonProperty("chargeKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ChargeKillsMostInGame { get; set; }

        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("earthshatterKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EarthshatterKills { get; set; }

        [JsonProperty("earthshatterKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EarthshatterKillsAvgPer10Min { get; set; }

        [JsonProperty("earthshatterKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EarthshatterKillsMostInGame { get; set; }

        [JsonProperty("fireStrikeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? FireStrikeKills { get; set; }

        [JsonProperty("fireStrikeKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? FireStrikeKillsAvgPer10Min { get; set; }

        [JsonProperty("fireStrikeKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? FireStrikeKillsMostInGame { get; set; }

        [JsonProperty("rocketHammerMeleeAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string RocketHammerMeleeAccuracy { get; set; }
    }

    internal partial class Roadhog : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal RoadhogHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class RoadhogHeroSpecific
    {
        [JsonProperty("enemiesHooked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesHooked { get; set; }

        [JsonProperty("enemiesHookedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EnemiesHookedAvgPer10Min { get; set; }

        [JsonProperty("enemiesHookedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesHookedMostInGame { get; set; }

        [JsonProperty("hookAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string HookAccuracy { get; set; }

        [JsonProperty("hookAccuracyBestInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string HookAccuracyBestInGame { get; set; }

        [JsonProperty("hooksAttempted", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HooksAttempted { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("wholeHogKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? WholeHogKills { get; set; }

        [JsonProperty("wholeHogKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? WholeHogKillsAvgPer10Min { get; set; }

        [JsonProperty("wholeHogKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? WholeHogKillsMostInGame { get; set; }
    }

    internal partial class Soldier76 : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal Soldier76HeroSpecific HeroSpecific { get; set; }
    }

    internal partial class Soldier76HeroSpecific
    {
        [JsonProperty("bioticFieldHealingDone", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BioticFieldHealingDone { get; set; }

        [JsonProperty("bioticFieldsDeployed", NullValueHandling = NullValueHandling.Ignore)]
        internal long? BioticFieldsDeployed { get; set; }

        [JsonProperty("helixRocketsKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HelixRocketsKills { get; set; }

        [JsonProperty("helixRocketsKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? HelixRocketsKillsAvgPer10Min { get; set; }

        [JsonProperty("helixRocketsKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HelixRocketsKillsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("tacticalVisorKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TacticalVisorKills { get; set; }

        [JsonProperty("tacticalVisorKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? TacticalVisorKillsAvgPer10Min { get; set; }

        [JsonProperty("tacticalVisorKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TacticalVisorKillsMostInGame { get; set; }
    }

    internal partial class Sombra : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal SombraHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class SombraHeroSpecific
    {
        [JsonProperty("enemiesEmpd", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesEmpd { get; set; }

        [JsonProperty("enemiesEmpdAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EnemiesEmpdAvgPer10Min { get; set; }

        [JsonProperty("enemiesEmpdMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesEmpdMostInGame { get; set; }

        [JsonProperty("enemiesHacked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesHacked { get; set; }

        [JsonProperty("enemiesHackedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EnemiesHackedAvgPer10Min { get; set; }

        [JsonProperty("enemiesHackedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? EnemiesHackedMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }
    }

    internal partial class Symmetra : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal SymmetraHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class SymmetraHeroSpecific
    {
        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("playersTeleported", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersTeleported { get; set; }

        [JsonProperty("playersTeleportedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? PlayersTeleportedAvgPer10Min { get; set; }

        [JsonProperty("playersTeleportedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersTeleportedMostInGame { get; set; }

        [JsonProperty("primaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string PrimaryFireAccuracy { get; set; }

        [JsonProperty("secondaryDirectHitsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SecondaryDirectHitsAvgPer10Min { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("sentryTurretsKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SentryTurretsKills { get; set; }

        [JsonProperty("sentryTurretsKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SentryTurretsKillsAvgPer10Min { get; set; }

        [JsonProperty("sentryTurretsKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SentryTurretsKillsMostInGame { get; set; }
    }

    internal partial class Torbjorn : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal TorbjornHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class TorbjornHeroSpecific
    {
        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("torbjornKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TorbjornKills { get; set; }

        [JsonProperty("torbjornKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? TorbjornKillsAvgPer10Min { get; set; }

        [JsonProperty("torbjornKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TorbjornKillsMostInGame { get; set; }

        [JsonProperty("turretsDamageAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? TurretsDamageAvgPer10Min { get; set; }

        [JsonProperty("turretsKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TurretsKills { get; set; }

        [JsonProperty("turretsKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? TurretsKillsAvgPer10Min { get; set; }

        [JsonProperty("turretsKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TurretsKillsMostInGame { get; set; }

        [JsonProperty("armorPacksCreated", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ArmorPacksCreated { get; set; }

        [JsonProperty("armorPacksCreatedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ArmorPacksCreatedAvgPer10Min { get; set; }

        [JsonProperty("armorPacksCreatedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ArmorPacksCreatedMostInGame { get; set; }

        [JsonProperty("moltenCoreKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MoltenCoreKills { get; set; }

        [JsonProperty("moltenCoreKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MoltenCoreKillsAvgPer10Min { get; set; }

        [JsonProperty("moltenCoreKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MoltenCoreKillsMostInGame { get; set; }
    }

    internal partial class Tracer : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal TracerHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class TracerHeroSpecific
    {
        [JsonProperty("healthRecovered", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HealthRecovered { get; set; }

        [JsonProperty("healthRecoveredAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? HealthRecoveredAvgPer10Min { get; set; }

        [JsonProperty("healthRecoveredMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HealthRecoveredMostInGame { get; set; }

        [JsonProperty("pulseBombKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombKills { get; set; }

        [JsonProperty("pulseBombKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombKillsMostInGame { get; set; }

        [JsonProperty("pulseBombsAttached", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombsAttached { get; set; }

        [JsonProperty("pulseBombsAttachedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombsAttachedAvgPer10Min { get; set; }

        [JsonProperty("pulseBombsAttachedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombsAttachedMostInGame { get; set; }

        [JsonProperty("pulseBombsKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombsKillsAvgPer10Min { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("pulseBombsKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombsKills { get; set; }

        [JsonProperty("pulseBombsKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PulseBombsKillsMostInGame { get; set; }
    }

    internal partial class Widowmaker : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal WidowmakerHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class WidowmakerHeroSpecific
    {
        [JsonProperty("scopedAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedAccuracy { get; set; }

        [JsonProperty("scopedAccuracyBestInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedAccuracyBestInGame { get; set; }

        [JsonProperty("scopedCriticalHits", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScopedCriticalHits { get; set; }

        [JsonProperty("scopedCriticalHitsAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string ScopedCriticalHitsAccuracy { get; set; }

        [JsonProperty("scopedCriticalHitsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ScopedCriticalHitsAvgPer10Min { get; set; }

        [JsonProperty("scopedCriticalHitsKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScopedCriticalHitsKills { get; set; }

        [JsonProperty("scopedCriticalHitsKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ScopedCriticalHitsKillsAvgPer10Min { get; set; }

        [JsonProperty("scopedCriticalHitsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ScopedCriticalHitsMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("venomMineKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? VenomMineKills { get; set; }

        [JsonProperty("venomMineKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? VenomMineKillsAvgPer10Min { get; set; }

        [JsonProperty("venomMineKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? VenomMineKillsMostInGame { get; set; }
    }

    internal partial class Winston : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal WinstonHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class WinstonHeroSpecific
    {
        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("jumpKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? JumpKills { get; set; }

        [JsonProperty("jumpPackKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? JumpPackKills { get; set; }

        [JsonProperty("jumpPackKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? JumpPackKillsAvgPer10Min { get; set; }

        [JsonProperty("jumpPackKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? JumpPackKillsMostInGame { get; set; }

        [JsonProperty("meleeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeleeKills { get; set; }

        [JsonProperty("meleeKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeleeKillsAvgPer10Min { get; set; }

        [JsonProperty("meleeKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MeleeKillsMostInGame { get; set; }

        [JsonProperty("playersKnockedBack", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersKnockedBack { get; set; }

        [JsonProperty("playersKnockedBackAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? PlayersKnockedBackAvgPer10Min { get; set; }

        [JsonProperty("playersKnockedBackMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersKnockedBackMostInGame { get; set; }

        [JsonProperty("primalRageKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PrimalRageKills { get; set; }

        [JsonProperty("primalRageKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PrimalRageKillsAvgPer10Min { get; set; }

        [JsonProperty("primalRageKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PrimalRageKillsMostInGame { get; set; }

        [JsonProperty("primalRageMeleeAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string PrimalRageMeleeAccuracy { get; set; }

        [JsonProperty("teslaCannonAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string TeslaCannonAccuracy { get; set; }

        [JsonProperty("weaponKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? WeaponKills { get; set; }
    }

    internal partial class WreckingBall : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal WreckingBallHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class WreckingBallHeroSpecific
    {
        [JsonProperty("playersKnockedBack", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersKnockedBack { get; set; }

        [JsonProperty("playersKnockedBackAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? PlayersKnockedBackAvgPer10Min { get; set; }

        [JsonProperty("playersKnockedBackMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? PlayersKnockedBackMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }
    }

    internal partial class Zarya : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal ZaryaHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class ZaryaHeroSpecific
    {
        [JsonProperty("averageEnergy", NullValueHandling = NullValueHandling.Ignore)]
        internal string AverageEnergy { get; set; }

        [JsonProperty("averageEnergyBestInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal string AverageEnergyBestInGame { get; set; }

        [JsonProperty("damageBlocked", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlocked { get; set; }

        [JsonProperty("damageBlockedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? DamageBlockedAvgPer10Min { get; set; }

        [JsonProperty("damageBlockedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? DamageBlockedMostInGame { get; set; }

        [JsonProperty("gravitonSurgeKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GravitonSurgeKills { get; set; }

        [JsonProperty("gravitonSurgeKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GravitonSurgeKillsAvgPer10Min { get; set; }

        [JsonProperty("gravitonSurgeKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GravitonSurgeKillsMostInGame { get; set; }

        [JsonProperty("highEnergyKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HighEnergyKills { get; set; }

        [JsonProperty("highEnergyKillsAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? HighEnergyKillsAvgPer10Min { get; set; }

        [JsonProperty("highEnergyKillsMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? HighEnergyKillsMostInGame { get; set; }

        [JsonProperty("primaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string PrimaryFireAccuracy { get; set; }

        [JsonProperty("projectedBarriersApplied", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ProjectedBarriersApplied { get; set; }

        [JsonProperty("projectedBarriersAppliedAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? ProjectedBarriersAppliedAvgPer10Min { get; set; }

        [JsonProperty("projectedBarriersAppliedMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ProjectedBarriersAppliedMostInGame { get; set; }

        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }
    }

    internal partial class Zenyatta : Hero
    {
        [JsonProperty("heroSpecific", NullValueHandling = NullValueHandling.Ignore)]
        internal ZenyattaHeroSpecific HeroSpecific { get; set; }
    }

    internal partial class ZenyattaHeroSpecific
    {
        [JsonProperty("secondaryFireAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal string SecondaryFireAccuracy { get; set; }

        [JsonProperty("selfHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealing { get; set; }

        [JsonProperty("selfHealingAvgPer10Min", NullValueHandling = NullValueHandling.Ignore)]
        internal double? SelfHealingAvgPer10Min { get; set; }

        [JsonProperty("selfHealingMostInGame", NullValueHandling = NullValueHandling.Ignore)]
        internal long? SelfHealingMostInGame { get; set; }

        [JsonProperty("transcendenceHealing", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TranscendenceHealing { get; set; }

        [JsonProperty("transcendenceHealingBest", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TranscendenceHealingBest { get; set; }
    }

    internal partial class TopHero
    {
        [JsonProperty("timePlayed", NullValueHandling = NullValueHandling.Ignore)]
        internal string TimePlayed { get; set; }

        [JsonProperty("timePlayedInSeconds", NullValueHandling = NullValueHandling.Ignore)]
        internal long? TimePlayedInSeconds { get; set; }

        [JsonProperty("gamesWon", NullValueHandling = NullValueHandling.Ignore)]
        internal long? GamesWon { get; set; }

        [JsonProperty("winPercentage", NullValueHandling = NullValueHandling.Ignore)]
        internal long? WinPercentage { get; set; }

        [JsonProperty("weaponAccuracy", NullValueHandling = NullValueHandling.Ignore)]
        internal long? WeaponAccuracy { get; set; }

        [JsonProperty("eliminationsPerLife", NullValueHandling = NullValueHandling.Ignore)]
        internal double? EliminationsPerLife { get; set; }

        [JsonProperty("multiKillBest", NullValueHandling = NullValueHandling.Ignore)]
        internal long? MultiKillBest { get; set; }

        [JsonProperty("objectiveKills", NullValueHandling = NullValueHandling.Ignore)]
        internal long? ObjectiveKills { get; set; }
    }

    internal partial class RawPlayerStats
    {
        internal static RawPlayerStats FromJson(string json) => JsonConvert.DeserializeObject<RawPlayerStats>(json, OverwatchCore.Data.Converter.Settings);

        internal static string ToJson(RawPlayerStats self) => JsonConvert.SerializeObject(self, OverwatchCore.Data.Converter.Settings);
    }

    internal static class Converter
    {
        internal static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                EAvgPer10MinConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class EAvgPer10MinConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(EAvgPer10Min) || t == typeof(EAvgPer10Min?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "00:00":
                    return EAvgPer10Min.The0000;
                case "00:01":
                    return EAvgPer10Min.The0001;
            }
            throw new Exception("Cannot unmarshal type EAvgPer10Min");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (EAvgPer10Min)untypedValue;
            switch (value)
            {
                case EAvgPer10Min.The0000:
                    serializer.Serialize(writer, "00:00");
                    return;
                case EAvgPer10Min.The0001:
                    serializer.Serialize(writer, "00:01");
                    return;
            }
            throw new Exception("Cannot marshal type EAvgPer10Min");
        }

        internal static readonly EAvgPer10MinConverter Singleton = new EAvgPer10MinConverter();
    }
}
